### ISSUE TITLE
Introduction and implementation of FTP into both the core and the Daemon

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#104]
In our entire system, we will be using FTP in order to access and update the file system of each service, this is going to take a bit of work to get fully implemented for MVP.  Below is a lit of the criteria that needs to be met in order to consider FTP fully implemented for MVP:

- User can create, delete, and modify ftp accounts on a per-service basis.
- When a service is created a corresponding ftp account is also created that is associated with the user who created the service 
- There is an FTP portal in the dashboard so that you can access ftp from the dashboard

I'm still conflicted on how I want to approach the FTP address but I am between one of two options.  The first options is an ftp router that take the login information and figures out which ftp server that login belongs to and routes the request to that ftp server, or we have each ftp server address that goes directly to that ftp server, but it that has to be stored separately from address that is used to connect to the daemon from the core.

The ftp login credentials should be formatted something like:
```
Address: ftp.duxcore.co | ftp.{daemon id fragment}.duxcore.co
Username: {user selected ftp username}.{service id fragment}
Password: randomly generated? the same password as the user?
Port: 22 or 2022
```

### TODO in core:
- [ ] Create Prisma Schema for ftp accounts that link to services
- [ ] Create service ftp module to manage ftp accounts in code
- [ ] API Route for the creation, deletion, and updating of FTP accounts
- [ ] API Route that the daemon can call to validate and authorize an ftp account.
- [ ] API Route to get all ftp accounts, get all ftp accounts by service, and by user

### TODO in daemon
- [ ] implement a determination as to weather the daemon is in dev mode 
- [ ] Have the core api address change based on weather it is in dev or production mode
- [ ] have the daemon contact the api when validating an ftp server.

### TODO in dashboard
- [ ] Implement service ftp account management
- [ ] Implement ftp client into service view
