### ISSUE TITLE
The plan for Duxcore...

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#2]
# What is Duxcore
Duxcore is going to be a hosting service which will allow for scalable, and hopefully affordable or even free, hosting.  This will be a service that will have to grow as time goes on so for now we will start with a checklist of what needs to be done to get this platform in any running order.

# Where to start
Well first and foremost, we are going to need a backend, which I have deemed will need to be determined by the community as to which language it will be written.  But as the backend is being written, it will be wrapped by the wrapper which will be used as the interface between anything and the backend.  So first we need to decide what the backend will be written in.  Once that has been decided we can begin the checklist.

## App's and their languages.
**api** - Node.js (Typescript)
**backend** - To be determined
**daemon** - To be determined
**website** - Next.js (Typescript)
**wrapper** - Node.js (Typescrip)

## TO-DO list
- [x] Determine what language the backend will be written in
- [ ] Begin drafting a figma design
- [ ] Setup the basic backend structure
     - [x] Create the structure
     - [ ] Setup websocket communication
     - [ ] Create User account system
     - [x] Create session system
- [ ] Create the wrapper to wrap the backend in
- [ ] Integrate the wrapper into the frontend ( with or without the figma mockup)
- [ ] Begin planning out what language the daemon should be written as well as how it will work

**Comment by HoloPanio** [comment]
To. The. Moon.

**Comment by HoloPanio** [comment]
to the moon

**Comment by samarmohan** [comment]
What’s the difference between api and backend?

**Comment by he1d1** [comment]
> 
> 
> What’s the difference between api and backend?

I'm guessing the API is the way the client can communicate with the code creating and managing the vps that are used for hosting

**Comment by HoloPanio** [comment]
> > What’s the difference between api and backend?
> 
> I'm guessing the API is the way the client can communicate with the code creating and managing the vps that are used for hosting

1. We are not just hosting vps's.  We will be hosting everything we can support
2. API is rest api and backend is, well the backend.

**Comment by he1d1** [comment]
> 
> 
> > > What’s the difference between api and backend?
> > 
> > 
> > I'm guessing the API is the way the client can communicate with the code creating and managing the vps that are used for hosting
> 
>     1. We are not just hosting vps's.  We will be hosting everything we can support
> 
>     2. API is rest api and backend is, well the backend.

have you considered using GraphQL rather than REST
