### ISSUE TITLE
Rough daemon/service integration bug report and what to do next

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#91]
### Bugs or problems
- [x] When daemon fails to connect, it just logs the `AxiosError` to console and doesn't return anything to the api.
- [x] When the `params` key is left out of the POST request body, an error is logged to console and nothing is returned to the api.
- [x] (Inconsistency) When creating a daemon, the schema has the `port` to be typeof `number` while the `wsPort` is typeof `string`.
- [x] There is currently no way to update a daemon server address through the api PATCH method.
- [x] When a daemon POST request is made that uses the same `regionDiscriminator` as another daemon, it returns an internal server error to the api that reads `\nInvalid '.create()' invocation in\n[REDACTED]\\duxcore\\core\\src\\interfaces\\daemons.ts:49:8\n\n  46   resourceCeil: { cpu, memory, disk },\n  47 }: NewDaemonData): Promise<DaemonManager> {\n  48   const newDaemon = await prismaInstance.daemon\n→ 49     .create(\n  Unique constraint failed on the fields: ('regionDiscriminator')`

### TODO
- [x] Move code to respective classes, modules, and interfaces.
- [x] Create an API route that can call the `start`. `stop`, `restart`, and `kill` op codes on the daemon.
- [x] Create a socket.io (or sim) ws interface at api route `/v1/ws`

**Comment by HoloPanio** [comment]
Websockets are now officially supported in manifestation, and I created a very basic POC with /v1/ws, and that completes this list
