### ISSUE TITLE
stuff todo

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#92]
### BUGS
*none for now*

### TODO
- [x] Make permissions more re-useable and consistent.  For example in `/core/src/api/routes/services/base.ts:126-130`, permission is being checked manually.  Perhaps making this into a middleware that could be easily replicated and updated to be used for all services now and in the future would be a good idea.
- [x] Implement a `GET /services/:service` api route to fetch any specific service(also using the aforementioned permission middleware.
- [x] Implement a `GET /services`  to get all services that a user would have access to.
- [x] Implement a route to get all services that a project contains.
- #100
- #101
- [x] Implement the ability to attach to a service's console in the daemon manager.
